# Generated by Django 4.2.4 on 2023-08-24 15:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/images')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('borrow_date', models.DateField(blank=True, default=datetime.datetime(2023, 8, 24, 15, 48, 49, 554664, tzinfo=datetime.timezone.utc), null=True)),
                ('borrow_period', models.IntegerField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='genre.genre')),
                ('status', models.ForeignKey(default='Available', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='status.status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
