# Generated by Django 4.2.4 on 2023-08-24 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 24, 17, 56, 39, 258395, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
