# Generated by Django 4.2.4 on 2023-08-25 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('books', '0003_alter_book_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 25, 17, 35, 33, 421610, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.ForeignKey(default='Available', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='status.status'),
        ),
    ]
