# Generated by Django 4.2.4 on 2023-08-27 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_borrow_date_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 27, 13, 7, 56, 45495, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
